apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: hasp
data:
  APP_ENV: production
  AWS_REGION: ap-northeast-2
  PREDICTOR_URL: http://kserve-predictor.hasp.svc.cluster.local
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: hasp
data:
  BOOTSTRAP_SERVERS: "replace-me:9092"
  REQUEST_TOPIC: inference-request
  RETRY_TOPIC: inference-retry
  DLQ_TOPIC: inference-dlq
  WORKER_CONSUMER_GROUP: inference-worker-group
  DYNAMODB_TABLE_NAME: sgs-hasp-inference-jobs
  MAX_RETRY_COUNT: "3"
  RETRY_JITTER_SECONDS: "5"
  RETRY_POLL_DELAY_SECONDS: "1"
