apiVersion: v1
kind: ServiceAccount
metadata:
  name: inference-api-sa
  namespace: hasp
  annotations: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inference-worker-sa
  namespace: hasp
  annotations: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-predictor-sa
  namespace: hasp
  annotations: {}
