name: Private Cloud Plan

on:
  push:
    branches:
      - feature/private
    paths:
      - .github/workflows/private-cloud-remote.yml
      - .github/workflows/private-cloud-plan.yml
      - .github/workflows/private-cloud-controller.yml
      - ha
      - private/ci/**
      - private/openstack/**
      - private/kubernetes-bootstrap/**
      - private/storage/**
      - private/gpu-worker/**
      - private/reverse-proxy/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    name: Remote CI
    uses: ./.github/workflows/private-cloud-remote.yml
    with:
      command: ci
    secrets: inherit
